In [25]:
import numpy as np
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
a.shape = (10,1)
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [28]:
b = np.empty(3)
b

array([0., 0., 0.])

In [35]:
c = np.linspace(2,12,6) # from 2 to 12, with 6 elements
c

array([ 2.,  4.,  6.,  8., 10., 12.])

In [40]:
d = np.array([10,20])
d

array([10, 20])

In [43]:
a_list=([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15])
e = np.array([a_list])
e

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [44]:
e.shape


(1, 3, 5)

In [45]:
?e

In [46]:
?e.shape

In [58]:
np.random.seed(0)
f=np.random.randint(10,size=7)
f


array([5, 0, 3, 3, 7, 9, 3])

In [59]:
f[0]

5

In [64]:
f[0:3]


array([5, 0, 3])

In [65]:
f[-1]

3

In [67]:
e < 3

array([[[ True,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [68]:
e[e>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [73]:
a_array+30

array([31, 32, 33, 34, 35])

In [75]:
b_array*5

array([30, 35, 40, 45, 50])

In [77]:
a_array[2]*5

15

In [78]:
a_array @ b_array

130

In [79]:
np.sort(b_array)

array([ 6,  7,  8,  9, 10])